CREATE DATABASE IF NOT EXISTS fizzbuzz;
USE fizzbuzz;
CREATE TABLE IF NOT EXISTS request (
    id INT NOT NULL AUTO_INCREMENT,
    request_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    value_1 INT NOT NULL,
    value_2 INT NOT NULL,
    replace_1 VARCHAR(255) NOT NULL,
    replace_2 VARCHAR(255) NOT NULL,
    max INT NOT NULL
);
